# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: macos-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install -g cordova
    cd $(Build.SourcesDirectory)/mytestapp
    echo $pwd
    npm install
    chmod +x ./build.sh
    ./build.sh
  displayName: 'npm install and build'


- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      **
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'CopyFiles'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)'
  displayName: 'PublishBuildArtifacts'


