# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: macos-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install -g cordova
    cd $(Build.SourcesDirectory)/mytestapp
    echo $pwd
    npm install
    npm run build
    echo "cd ../mycordova/"
    $ANDROID_HOME/tools/bin/sdkmanager --uninstall  'build-tools;32.0.0'
    $ANDROID_HOME/tools/bin/sdkmanager --uninstall  'build-tools;31.0.0'
    $ANDROID_HOME/tools/bin/sdkmanager --install  'build-tools;30.0.0'

    cd $(Build.SourcesDirectory)/mycordova/
    echo "cordova build"
    cordova build

    echo "$(Build.SourcesDirectory)/mytestapp"
    cd $(Build.SourcesDirectory)/mytestapp

    echo "copy mytestapp www"
    cp -R $(Build.SourcesDirectory)/mytestapp/dist/mytestapp/* $(Build.SourcesDirectory)/mycordova/platforms/android/app/src/main/assets/www

  displayName: 'npm install and build'


- task: CopyFiles@1
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/mycordova/platforms/android/app'
    Contents: |
      **/build/*
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'CopyFiles'

- task: PublishBuildArtifacts@3
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
  displayName: 'PublishBuildArtifacts'


